### ISSUE TITLE
when doing a full F5 refresh the left corner icon disappears

### ISSUE THREAD

**Issue by paulvanbladel** [beeman/loopback-angular-admin#33]
I know, in a SPA one should not do a full refresh (but users do)
![image](https://cloud.githubusercontent.com/assets/4886272/5873002/f72a27b4-a2f1-11e4-9b80-70f8ad62d1bf.png)
As you can see, the user info panel gets messed up.
Cheers
paul.

**Comment by beeman** [comment]
Thanks for this issue! Should be fixed in the 'develop' branch! :)

**Comment by tuanpmt** [comment]
I think problem is not solved, when i refresh, I do not find the login information is stored. token is not stored in cookies. You must save the login token into cookies when logged, and use it to log in and retrieve user information every time refresh the webpage.

**Comment by josx** [comment]
If I log in and reload, user info is lost but still showing dashboard (like i am logged in)
Is this a known bug?
